### ISSUE TITLE
in process_insn_tokens KeyError: 'J2_jump' 

### ISSUE THREAD

**Issue by peanuts62** [google/binja-hexagon#8]
I following [setup & build](https://github.com/google/binja-hexagon/blob/main/docs/setup.md) on MacOS with python3.8 and Cmake 3.21.3,but I stuck on this error.
```
[ 85%] Generating insn_text_funcs_generated.cc
Processing 2228 tags in parallel
Done processing tag # 0
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/xxxxx/Desktop/xxx/decomplie_tools/binja-hexagon/plugin/gen_insn_text_funcs.py", line 602, in gen_insn_text_func
    tokens = process_insn_tokens(tag, regs, imms)
  File "/Users/xxxxx/Desktop/xxx/decomplie_tools/binja-hexagon/plugin/gen_insn_text_funcs.py", line 595, in process_insn_tokens
    beh = behdict[tag]
KeyError: 'J2_jump'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/xxxxx/Desktop/xxx/decomplie_tools/binja-hexagon/plugin/gen_insn_text_funcs.py", line 681, in <module>
    main()
  File "/Users/xxxxx/Desktop/xxx/decomplie_tools/binja-hexagon/plugin/gen_insn_text_funcs.py", line 652, in main
    tag_to_fbody = process_all_tags(tagregs, tagimms)
  File "/Users/xxxxx/Desktop/xxx/decomplie_tools/binja-hexagon/plugin/gen_insn_text_funcs.py", line 622, in process_all_tags
    tag_to_fbody[tag] = future.result() # myslef added reslut error
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
KeyError: 'J2_jump'
make[2]: *** [plugin/insn_text_funcs_generated.cc] Error 1
make[1]: *** [plugin/CMakeFiles/plugin_lib.dir/all] Error 2
make: *** [all] Error 2
```
I find dict of `behdict` haven't added any element when 'gen_insn_text_funcs.py'  use it to get some value 'beh = behdict[tag]'

**Comment by peanuts62** [comment]
I build it successfully by using python3.7 on MacOS.
Thank you for your work. :)
